### PR TITLE
Visitor visiting dashboard is redirected when not logged in

### LINKED ISSUE #53: Dashboard with no login
As a visitor
When I am not logged in
When I visit "/dashboard"
I am redirected to the main page

### PR DESCRIPTION
**Pull request by russelleh**
Closes #53

### CODE REVIEW

**Comment by ChrisCenatie** [comment]
Have duplicate specs with different names. Delete one.

**Comment by russelleh** [comment]
Sorry, I saved the old one after renaming it.

**Comment by ChrisCenatie** [comment]
This looks good to go. Woof!

**Comment by jbrr** [comment]
I like the part where it redirects the user

**Pull request merged**
