### PR TITLE
This closes #41

### LINKED ISSUE #41: Adding loans to the cart
Background: Loans, and a user that is not logged in

Title: 

As a visitor
When I visit any page with an loan on it
I should see a link or button for "Add to Cart"
When I click "Add to cart" for that loan
And I click a link or button to view cart
And my current path should be "/cart"
And I should see a small image, title, description and price for the loan I just added
And there should be a "total" price for the cart that should be the sum of all loans in the cart

When I login
And I visit "/cart"
Then I should see all of the data that was there when I was not logged in

### PR DESCRIPTION
**Pull request by ChrisCenatie**
https://en.wikipedia.org/wiki/Hug

### CODE REVIEW

**Comment by ChrisCenatie** [comment]
No violations. Woof!

**Comment by russelleh** [comment]
Pretty straightforward.

**Comment by russelleh** [comment]
You forgot to say "Closes #41" in the comments

**Comment by jbrr** [comment]
Sounds about right. I like it.

**Comment by ChrisCenatie** [comment]
Checkout my hug link. Everyone needs hugs

**Comment by jbrr** [comment]
https://www.youtube.com/watch?v=80yjtJFf-v0

**Pull request merged**
