### PR TITLE
Green

### LINKED ISSUE #42: Removing an loan from my cart
Background: My cart has an loan in it

As a visitor
When I visit "/cart"
And I click link "Remove"
Then my current page should be "/cart"
And I should see a message styled in green
And the message should say "Successfully removed SOME_LOAN from your cart."
And the title "SOME_LOAN" should be a link to that item in case the user wants to add it back
And I should not see the loan listed in cart

### PR DESCRIPTION
**Pull request by ChrisCenatie**
Green
Closes #42

### CODE REVIEW

**Comment by russelleh** [comment]
Green

**Comment by mbburch** [comment]
Green.

**Comment by jbrr** [comment]
Green!

**Comment by jbrr** [comment]
Aw, c'mon guys!!

**Comment by russelleh** [comment]
@jbrr https://en.wikipedia.org/wiki/High_five#.22Too_slow.22

**Comment by ChrisCenatie** [comment]
The blues smell better

**Pull request merged**
