### PR TITLE
Checkout create orders

### LINKED ISSUE #90: User can check out
As a user,
When I add loans to the cart, 
and I click on "Checkout",
and enter billing information,
and I click on "Submit",
then my order has been placed,
and my cart is cleared,
and I am redirected to a summary of the order.

### PR DESCRIPTION
**Pull request by ChrisCenatie**
Closes #90

### CODE REVIEW

**Comment by ChrisCenatie** [comment]
Up yours hound

**Comment by jbrr** [comment]
lol hound

**Comment by mbburch** [comment]
Wow... I think hound should just start cursing at you. Thanks for working so hard on this branch, Chris! Should we merge in the morning?

**Comment by jbrr** [comment]
I don't know, he was thinking about working more tonight since he was in the zone. @ChrisCenatie, want this merged tonight once the hound complaints are fixed?

**Comment by jbrr** [comment]
Woof

**Comment by mbburch** [comment]
Well that was an epic hound session. Woof to Chris. Way to use that space bar.

**Pull request merged**
