### PR TITLE
Start paperclip functionality, load loan images on loan index page.

### PR DESCRIPTION
**Pull request by mbburch**
Paperclip is installed but we cannot move forward with it until we create the login page, as we want a user to be logged in to create a loan. Hold off on this until we talk with product owner on Thursday. We added different loan images to the loan index.

### CODE REVIEW

**Comment by mbburch** [comment]
Fixed hash syntax from hound. Should be good to go.

**Comment by jbrr** [comment]
We changed the carousel to display different images, but they're just hard coded in. I guess that's a design decision, but I'm alright with that. If we have "featured" loans, I think those will have to be manually set, since we won't have the user base to write some algorithm to calculate which loans are generating the most views or something like that.

**Comment by jbrr** [comment]
Also, more eyes are always better, make sure you guys don't see my AWS key anywhere in there. It should be in `.gitignore`, but I'm still a little nervous about it.

**Comment by russelleh** [comment]
Looks good. Good to see there aren't any AWS keys. It'll be nice when we get everything looking good.

**Comment by russelleh** [comment]
We should probably put (Closes #20) in the comment next time. We keep forgetting

**Pull request merged**
