### PR TITLE
Create new tables

### PR DESCRIPTION
**Pull request by jbrr**
Added orders, order items, and statuses tables. I think this design should work, but this is pretty important and not the easiest thing to change later, so we should all probably take a look and sign off on this before merging it.

### CODE REVIEW

**Comment by jbrr** [comment]
Hound is complaining about seed data. I guess those variables are pretty useless. What do y'all think?

**Comment by jbrr** [comment]
Hound's happy, I'm happy.

**Comment by mbburch** [comment]
It looks like you got all the components of the tables linked together well. Are there any tests for these yet? Thanks guys!

**Comment by mbburch** [comment]
ready for merging?

**Comment by jbrr** [comment]
Yeah, I'm not totally sure that we need tests, we aren't doing anything yet with the relationships. The tables have documentation in the schema file. We can try and write some tests if you'd like, though.

**Comment by jbrr** [comment]
Closes #87 and #88

**Comment by russelleh** [comment]
Cool beans.

**Pull request merged**
