### PR TITLE
Add navbar partial

### PR DESCRIPTION
**Pull request by jbrr**
Still working on the loans index page, but the navbar should be functional

### CODE REVIEW

**Comment by jbrr** [comment]
There are multiple Hound complaints, but they're all about Bootstrap files. I'm not too concerned about that, I don't know how y'all feel about it.

**Comment by russelleh** [comment]
@houndci Please forward your complaints to the JQuery foundation

**Comment by ChrisCenatie** [comment]
Woof

**Comment by mbburch** [comment]
Appears that all hound is indeed bootstrap. Navbar looks good, and we can come back and add glyphicons later.

**Pull request merged**
