### PR TITLE
Visitor viewing loans can view loans

### LINKED ISSUE #9: Visitor can view loans
The database has loans, and each has a name, description, image, and price.

As a visitor
When I visit "/loans"
I can see all existing loans

### PR DESCRIPTION
**Pull request by jbrr**
Closes #9

### CODE REVIEW

**Comment by ChrisCenatie** [comment]
I love these changes!!!! Lets converse https://www.youtube.com/watch?v=47D9-U8hn5I

**Comment by russelleh** [comment]
That commit message is a little redundant...

**Comment by russelleh** [comment]
Put "Closes #9" in the comment so it automatically closes on Waffle

**Comment by jbrr** [comment]
Good call Russell, I appreciate your comment. Chris, I would converse.

**Comment by russelleh** [comment]
Whoops, we forgot images...

**Pull request merged**
