### PR TITLE
Add category show page, implement category functionality on navbar

### LINKED ISSUE #27: Style category show page
Style category show page to look like loan index page

### PR DESCRIPTION
**Pull request by jbrr**
Added category show page as well as navbar dropdown menu functionality. We probably could do a fair amount of refactoring, a lot of code is repeated between loan index page and category show page, but we can add an issue for that. For now, it works, and all tests are passing.

Closes #27

### CODE REVIEW

**Comment by russelleh** [comment]
Having a comma in your commit message is probably a red flag that you should commit more

**Comment by mbburch** [comment]
We need to pull style out of carousel images in loan index. It is there for now as Russell and Chris were working in the CSS file. Add this to CSS file instead.

**Comment by mbburch** [comment]
Passive aggressive comments are probably a sign that you should talk to someone in person.

**Comment by ChrisCenatie** [comment]
,

**Comment by russelleh** [comment]
@mbburch Please use the @ symbol when referring to other users

**Comment by ChrisCenatie** [comment]
@,

**Comment by jbrr** [comment]
Thanks for all the good GitHub tricks, team

**Pull request merged**
