### PR TITLE
Logging In

### LINKED ISSUE #52: Logging In

### PR DESCRIPTION
**Pull request by russelleh**
Not finished with authentication, but got some logging in functionality done. Closes #52

### CODE REVIEW

**Comment by jbrr** [comment]
Woof!

**Comment by jbrr** [comment]
Looks good to me, since we paired on this. We'll wait for @mbburch and @ChrisCenatie to take a look at it.

**Comment by mbburch** [comment]
Cool. Glad you got it to work with /dashboard path. @ChrisCenatie can merge when he's ready!

**Comment by ChrisCenatie** [comment]
This looks good. We'll figure out how to integrate this with the cart after we complete the add, delete, updates of cart for visitors. Woof!

**Pull request merged**
