### PR TITLE
make image sizing consistent

### PR DESCRIPTION
**Pull request by mbburch**

### CODE REVIEW

**Comment by mbburch** [comment]
There are still a few hound violations because it told me to order things two different ways. I didn't merge the css it asked me to merge, as things didn't work correctly when I did. Check and see how the images look. Also, I made sure links on category show page linked to individual loans, as they weren't until now.

**Comment by ChrisCenatie** [comment]
I will check this out

**Comment by ChrisCenatie** [comment]
Uh-oh, I did find a bug. When a user adds the same item with a quantity of more than ten, the quantity shows up a 1 on the cart-index page. Do we want to limit the number of items a person can checkout up to ten?

**Comment by ChrisCenatie** [comment]
I'm going to run this on our production environment real quick before merging

**Comment by mbburch** [comment]
We need to find better copyright free images and replace the ones we have.

**Pull request merged**
